// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpLHHWzjsgJkeDUFmCkW2dDX14-BORSLQ',
    appId: '1:824440030133:web:b1692d61423ce527e44ffc',
    messagingSenderId: '824440030133',
    projectId: 'safezone-9f5a9',
    authDomain: 'safezone-9f5a9.firebaseapp.com',
    storageBucket: 'safezone-9f5a9.appspot.com',
    measurementId: 'G-05X4SHLSEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsj4kDe1GQTFSK3rX4Xx-fswqiBEAEe4',
    appId: '1:824440030133:android:5f81be414f4380bae44ffc',
    messagingSenderId: '824440030133',
    projectId: 'safezone-9f5a9',
    storageBucket: 'safezone-9f5a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1x5_0yurqiqrufeVVAWO1aeTKfEnsNw',
    appId: '1:824440030133:ios:64b500871079143ce44ffc',
    messagingSenderId: '824440030133',
    projectId: 'safezone-9f5a9',
    storageBucket: 'safezone-9f5a9.appspot.com',
    iosBundleId: 'com.example.safeZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1x5_0yurqiqrufeVVAWO1aeTKfEnsNw',
    appId: '1:824440030133:ios:64b500871079143ce44ffc',
    messagingSenderId: '824440030133',
    projectId: 'safezone-9f5a9',
    storageBucket: 'safezone-9f5a9.appspot.com',
    iosBundleId: 'com.example.safeZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpLHHWzjsgJkeDUFmCkW2dDX14-BORSLQ',
    appId: '1:824440030133:web:50a3eebf48bf2c10e44ffc',
    messagingSenderId: '824440030133',
    projectId: 'safezone-9f5a9',
    authDomain: 'safezone-9f5a9.firebaseapp.com',
    storageBucket: 'safezone-9f5a9.appspot.com',
    measurementId: 'G-E31BH9741F',
  );
}
